apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scalechat-chat-db
spec:
  selector:
    matchLabels:
      db: scalechat-chat-db
  serviceName: scalechat-chat-db-service
  replicas: 1
  template:
    metadata:
      labels:
        db: scalechat-chat-db
    spec:
      containers:
      - name: scalechat-chat-db
        image: postgres:13
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: data
        volumeMounts:
        - name: chatdata
          mountPath: /var/lib/postgresql/data
        env:
          - name: "POSTGRES_DB"
            value: "scalechat_chat_db"
          - name: "POSTGRES_USER"
            value: "user"
          - name: "POSTGRES_PASSWORD"
            value: "password" 

  volumeClaimTemplates:
  - metadata:
      name: chatdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "scalechat-chat-db-service"
spec:
  selector:
    db: scalechat-chat-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: scalechat_chat:0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: "PORT"
              value: "0.0.0.0:80"
            - name: "DB_CONN"
              value: "postgres://user:password@scalechat-chat-db-service:5432/scalechat_chat_db?sslmode=disable"
            - name: "DB"
              value: "postgres"
            - name: "SECRET"
              value: "somerandomsecretsharedamongservicesreplacewithak8ssecretifyoureusingforproductionbutyoushouldntbecopypastinganythingfromhereanyway"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-service
spec:
  type: NodePort
  selector:
    app: chat-service
  ports:
  - port: 9999
    targetPort: 80
    nodePort: 30001
